<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net10.0-android</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Include="Bios\Fonts\font1.raw" />
      <EmbeddedResource Include="Bios\Fonts\font2.raw" />
      <EmbeddedResource Include="Host\Window\Assets\fa-solid-900.ttf" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
      <PackageReference Include="MonoMod.RuntimeDetour" Version="25.3.6" />
      <PackageReference Include="Silk.NET" Version="2.22.0" />
      <PackageReference Include="Silk.NET.OpenGL.Extensions.ImGui" Version="2.22.0" />
      <PackageReference Include="Silk.NET.SDL" Version="2.23.0" />
      <PackageReference Include="StbImageSharp" Version="2.30.15" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
      <PackageReference Include="NativeFileDialogNET" Version="2.0.2" />
      <PackageReference Include="Silk.NET.OpenAL.Soft.Native" Version="1.23.1" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
    </ItemGroup>

</Project>
